# Generated by Django 3.0.8 on 2020-07-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('cep', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=45)),
                ('bairro', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=45)),
                ('uf', models.CharField(max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=45, null=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
    ]
